[package]
name = "chipioindustries/rodux"
description = "A fork of Rodux which introduces additional functionality."
version = "3.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
Llama = "freddylist/llama@1.1.1"